# Railway Riders Travel Analysis

In [ ]:
UK Railway Travel Analysis is a Python-based data analysis project using mock National Rail ticket data from January to April 2024.
The project explores railway travel patterns, ticket sales, pricing, revenue, routes, and service performance.
The analysis focuses on:
Identifying the most popular travel routes
Analysing peak travel times
Comparing revenue by ticket type and class
Evaluating ticket prices and journey patterns
Analysing on-time vs. delayed journeys
Identifying factors that may contribute to train delays
Creating visualisations to communicate key findings and trends

# Column Description

In [ ]:
Transaction ID
Unique identifier for each train ticket purchase

Date of Purchase
Date when the ticket was purchased

Time of Purchase
Time when the ticket was purchased

Purchase Type
Indicates whether the ticket was purchased online or at a train station

Payment Method
Method used to purchase the ticket, such as Contactless, Credit Card, or Debit Card

Railcard
Indicates whether the passenger has a Railcard and the type of Railcard

Ticket Class
Class of the ticket, such as Standard or First

Ticket Type
Type of ticket, such as Advance, Off-Peak, or Anytime

Price
Final cost of the ticket

Departure Station
Station where the passenger boards the train

Arrival Destination
Station where the passenger exits the train

Date of Journey
Date on which the train journey takes place

Departure Time
Time when the train departs from the departure station

Arrival Time
Scheduled time when the train is expected to arrive

Actual Arrival Time
Actual time when the train arrives at the destination

Journey Status
Indicates whether the journey was on time, delayed, or cancelled

Reason for Delay
Reason for the train delay or cancellation

Refund Request
Indicates whether the passenger requested a refund after a delay or cancellation

# Raw Data

In [68]:
import pandas as pd

# Load raw data
df = pd.read_csv(r"C:\Users\HP\Documents\railway.csv")

# Preview data
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

# Checking Duplicates

In [69]:
# Check duplicate rows
df.duplicated().sum()

print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Transaction IDs:", df["Transaction ID"].duplicated().sum())

Duplicate rows: 0
Duplicate Transaction IDs: 0

In [22]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

# Changing DataType

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  object
 1   Date of Purchase     31653 non-null  object
 2   Time of Purchase     31653 non-null  object
 3   Purchase Type        31653 non-null  object
 4   Payment Method       31653 non-null  object
 5   Railcard             10735 non-null  object
 6   Ticket Class         31653 non-null  object
 7   Ticket Type          31653 non-null  object
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  object
 10  Arrival Destination  31653 non-null  object
 11  Date of Journey      31653 non-null  object
 12  Departure Time       31653 non-null  object
 13  Arrival Time         31653 non-null  object
 14  Actual Arrival Time  29773 non-null  object
 15  Journey Status       31653 non-null  object
 16  Reason for Delay     4172 non-null   object
 17  Refund Request       31653 non-null  object
dtypes: int64(1), object(17)
memory usage: 4.3+ MB

In [21]:
# Convert date columns
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])
df["Date of Journey"] = pd.to_datetime(df["Date of Journey"])

# Convert time columns
df["Time of Purchase"] = pd.to_datetime(df["Time of Purchase"], format="%H:%M:%S").dt.time
df["Departure Time"] = pd.to_datetime(df["Departure Time"], format="%H:%M:%S").dt.time
df["Arrival Time"] = pd.to_datetime(df["Arrival Time"], format="%H:%M:%S").dt.time

df["Actual Arrival Time"] = pd.to_datetime(df["Actual Arrival Time"], format="%H:%M:%S", errors="coerce").dt.time

In [24]:
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

In [36]:
# Convert time columns to datetime format

time_columns = [
    "Time of Purchase",
    "Departure Time",
    "Arrival Time",
    "Actual Arrival Time"
]

for col in time_columns:
    df[col] = pd.to_datetime(df[col], format="%H:%M:%S", errors="coerce")

df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request,Month of Travel
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,1900-01-01 11:00:00,1900-01-01 13:30:00,1900-01-01 13:30:00,On Time,No Delay,No,January
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,1900-01-01 09:45:00,1900-01-01 11:35:00,1900-01-01 11:40:00,Delayed,Signal Failure,No,January
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,Not Applicable,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,1900-01-01 18:15:00,1900-01-01 18:45:00,1900-01-01 18:45:00,On Time,No Delay,No,January
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,Not Applicable,Standard,Advance,13,London Paddington,Reading,2024-01-01,1900-01-01 21:30:00,1900-01-01 22:30:00,1900-01-01 22:30:00,On Time,No Delay,No,January
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,Not Applicable,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,1900-01-01 16:45:00,1900-01-01 19:00:00,1900-01-01 19:00:00,On Time,No Delay,No,January

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  object
 1   Date of Purchase     31653 non-null  datetime64[ns]
 2   Time of Purchase     31653 non-null  datetime64[ns]
 3   Purchase Type        31653 non-null  object
 4   Payment Method       31653 non-null  object
 5   Railcard             31653 non-null  object
 6   Ticket Class         31653 non-null  object
 7   Ticket Type          31653 non-null  object
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  object
 10  Arrival Destination  31653 non-null  object
 11  Date of Journey      31653 non-null  datetime64[ns]
 12  Departure Time       31653 non-null  datetime64[ns]
 13  Arrival Time         31653 non-null  datetime64[ns]
 14  Actual Arrival Time  31653 non-null  datetime64[ns]
 15  Journey Status       31653 non-null  object
 16  Reason for Delay     31653 non-null  object
 17  Refund Request       31653 non-null  object
 18  Month of Travel      31653 non-null  object
dtypes: datetime64[ns](6), int64(1), object(12)
memory usage: 4.6+ MB

# Checking Null

In [70]:
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

# Fulling the Null Value

In [39]:
df["Railcard"] = df["Railcard"].fillna("Not Applicable")

df["Reason for Delay"] = df["Reason for Delay"].fillna("No Delay")

df["Actual Arrival Time"] = df["Actual Arrival Time"].fillna(
    df["Arrival Time"]
)

In [40]:
df["Railcard"].isnull().sum()

np.int64(0)

In [41]:
df["Reason for Delay"].isnull().sum()

np.int64(0)

In [42]:
df["Actual Arrival Time"].isnull().sum()

np.int64(0)

In [43]:
df.isnull().sum()

Transaction ID         0
Date of Purchase       0
Time of Purchase       0
Purchase Type          0
Payment Method         0
Railcard               0
Ticket Class           0
Ticket Type            0
Price                  0
Departure Station      0
Arrival Destination    0
Date of Journey        0
Departure Time         0
Arrival Time           0
Actual Arrival Time    0
Journey Status         0
Reason for Delay       0
Refund Request         0
Month of Travel        0
dtype: int64

In [44]:
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request,Month of Travel
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,1900-01-01 11:00:00,1900-01-01 13:30:00,1900-01-01 13:30:00,On Time,No Delay,No,January
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,1900-01-01 09:45:00,1900-01-01 11:35:00,1900-01-01 11:40:00,Delayed,Signal Failure,No,January
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,Not Applicable,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,1900-01-01 18:15:00,1900-01-01 18:45:00,1900-01-01 18:45:00,On Time,No Delay,No,January
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,Not Applicable,Standard,Advance,13,London Paddington,Reading,2024-01-01,1900-01-01 21:30:00,1900-01-01 22:30:00,1900-01-01 22:30:00,On Time,No Delay,No,January
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,Not Applicable,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,1900-01-01 16:45:00,1900-01-01 19:00:00,1900-01-01 19:00:00,On Time,No Delay,No,January

# New Column "Month of Travel"

In [45]:
# Create Month column from Date of Journey
df["Month of Travel"] = df["Date of Journey"].dt.month_name()

df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request,Month of Travel
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,1900-01-01 11:00:00,1900-01-01 13:30:00,1900-01-01 13:30:00,On Time,No Delay,No,January
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,1900-01-01 09:45:00,1900-01-01 11:35:00,1900-01-01 11:40:00,Delayed,Signal Failure,No,January
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,Not Applicable,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,1900-01-01 18:15:00,1900-01-01 18:45:00,1900-01-01 18:45:00,On Time,No Delay,No,January
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,Not Applicable,Standard,Advance,13,London Paddington,Reading,2024-01-01,1900-01-01 21:30:00,1900-01-01 22:30:00,1900-01-01 22:30:00,On Time,No Delay,No,January
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,Not Applicable,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,1900-01-01 16:45:00,1900-01-01 19:00:00,1900-01-01 19:00:00,On Time,No Delay,No,January

# Checking Inconsistency in Data

In [64]:
# Check unique values in categorical columns

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Transaction ID
Transaction ID
da8a6ba8-b3dc-4677-b176    1
57270295-4c04-41ef-8d60    1
e69c5905-c982-4362-8413    1
79d56b17-19ee-4f2d-a279    1
7dbec16c-8f83-442c-a7a2    1
                          ..
0bbcdb6e-1da7-4e88-9ddd    1
625339b0-33be-45b7-acf8    1
2829b4fd-802d-480f-8346    1
b8d53a45-b49b-453b-81b4    1
1d5d89a2-bde5-410f-8f91    1
Name: count, Length: 31653, dtype: int64

 Purchase Type
Purchase Type
Online     18521
Station    13132
Name: count, dtype: int64

 Payment Method
Payment Method
Credit Card    19136
Contactless    10834
Debit Card      1683
Name: count, dtype: int64

 Railcard
Railcard
Not Applicable    20918
Adult              4846
Disabled           3089
Senior             2800
Name: count, dtype: int64

 Ticket Class
Ticket Class
Standard       28595
First Class     3058
Name: count, dtype: int64

 Ticket Type
Ticket Type
Advance     17561
Off-Peak     8752
Anytime      5340
Name: count, dtype: int64

 Departure Station
Departure Station
Manchester Piccadilly    5650
London Euston            4954
Liverpool Lime Street    4561
London Paddington        4500
London Kings Cross       4229
London St Pancras        3891
Birmingham New Street    2136
York                      927
Reading                   594
Oxford                    144
Edinburgh Waverley         51
Bristol Temple Meads       16
Name: count, dtype: int64

 Arrival Destination
Arrival Destination
Birmingham New Street    7742
Liverpool Lime Street    5022
York                     4019
Manchester Piccadilly    3968
Reading                  3920
London Euston            1567
London St Pancras         749
Oxford                    623
London Paddington         351
Leicester                 337
Sheffield                 272
Durham                    258
Leeds                     255
Peterborough              242
Swindon                   228
Tamworth                  227
Nuneaton                  219
Doncaster                 211
Crewe                     193
Stafford                  190
Edinburgh Waverley        178
Nottingham                158
Edinburgh                 154
Bristol Temple Meads      144
Wolverhampton             115
London Kings Cross         84
London Waterloo            68
Coventry                   65
Didcot                     48
Cardiff Central            16
Wakefield                  15
Warrington                 15
Name: count, dtype: int64

 Journey Status
Journey Status
On Time      27481
Delayed       2292
Cancelled     1880
Name: count, dtype: int64

 Reason for Delay
Reason for Delay
No Delay              27481
Weather                 995
Technical Issue         707
Signal Failure          523
Singal Failure          447
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64

 Refund Request
Refund Request
No     30535
Yes     1118
Name: count, dtype: int64

 Month of Travel
Month of Travel
March       8117
January     8111
April       7781
February    7644
Name: count, dtype: int64

In [66]:
# Combine Signal Failure with Singal Failure

df.loc[df["Reason for Delay"] =="Singal Failure" , "Reason for Delay"] = "Signal Failure"

df["Reason for Delay"].value_counts()

Reason for Delay
No Delay              27481
Weather                 995
Signal Failure          970
Technical Issue         707
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64